sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-124
env:
  global:
    -
      # LTD_AWS_ID
      secure: ZxSJ8+8oTIlvRaIkF6qWiPocz1VsoDG5NFfB4q16foFDcxMILKiLhOzw+lPiCD2OhCIFZGBHrSavc4pmOEE5TDiTIf8HsP/h+VS6nSdwed+3G3nyIBZY0eaVocTHDL+3kqLpaRYokpEe2iFtSzc0UnC1FPgPQntxlkFm39gxdF1KfwPafg7AeW55k0H46VOix75dAVoXHLJ7nztkWiFK+UAM550BieRmTts07N+j8mPYHwa+ba0f1KMBvNLKj5KRjI9TO/xu/1XhRSdLO9Q7BXrAL/Dhm7krS1/KnNpUSBCdWkbmclPG4kHsBucjP34kTIkiYFByffpvNQHUNscfCxt26ECt4idNOgv8SNoFXtxUkVdsN+Qrhwn6bs1mLncshTXfjIB0TTCop3yi2xTHBvZ0TwwiPnscUXGpTrUU480C7eQ+MgID2kkuF8HG8luyvRg55FJnyjPpn2Co1RwbND0Lu03jiIpDKKD94LZw9v6Fqe1qSVlV23o0PFUyHW7ImmS8p36hEESIHLAjZMYYBCrTbtY8Xseah3aN3zdmOEO1yHXDkFFdhMuM164Oki/wdW+nwtF2eHmquwKFga+UFZCL8RPX+dx4bQ7zboXqnbc3vk9hg3h9oLXnqONAibVDHmeFCqzAM8AqKFmlkhMPk6cnljuMEwUYJiVpxrl+JXc=
    -
      # LTD_AWS_SECRET
      secure: qX5DoybQcNRJFGo0rcbwkUYvgXCn2EGdfSFknfUmmdtCOcehNLk/V4zmJjBD4a3LHzwN3NpARFhibiSK3hsD4TkWbkNT8zFdMkn1EI6mQmS4QFGFG7o7MdE2H1nBtd2hBm+WOa3JTsnsR6p8gczBoEGJYi+10KUFMdqCcuy6V6v+stxHwFBfClT7ae7ARQPTR1RGiAY5v6xCWwa25d9+rpb8pEXjfdb729Aqw7CLuHA2/2mSwlwNMRiDj1ALgHxrMUE7miuAyb/q1b4gRlBHktImBol0jemrzCLEF6D7415EYmlHbxegQfsSWE7gIzAJ74tdJWRimOAKLphrnzHPmaLXlQfkkHzbvLhpF4Lk40kncH8UEXS3fygNyu8h6r2plUTXNIu0PGeLnSFkn3je71ujVJj6Cn+oP0Ce/9rPcZq+fOyO5f89NmwlKwdzBa0c02trRrRb5amFq+0mBxyu1QihrG70I21FBFFS2ECCLhmE/clPqA2SvX7rZyVgw8cLcP/S6UgcjRYbbgkgJHlI7JJEvBNCoGfJ4s3nnZTirxwCXg4+bBfAFKDCEWQmbHapRZEsNDd/8hIf3eOJpwKkEanqsH6FtMq4+i6G6QPIUALH5TNlx+/Vceen89sbVbPlqETFv3s7H6JOuJTASbSwjnLa4BlB45X794N0yl1s+TM=
    -
      # LTD_USERNAME
      secure: n426hB/MiRf0jP1YPvTHI3PdIpcFLdBKwdEg70JSLhZk01ecFyB2uiuwGYq89bvugq3cLcXzOKK+Y4pysaGDTfmiWov1YfoFGtq+00fhAC4aFRpyzGXHB13IClHXAr9fWmLJU7eolYMMJehpopYGgeVFx0MurcUuVv2qQbjs7mJ7G1Tl/1XHni/JWtuvc+Jt6dXuQCgwX8E1kAS9sSd3LbJ4PoAvozHk2zTlav5FT5mLmvRVWbSCY3L2h03y3MJt7bnVj9zroG6AUEqO5JXnaxMd0F9+aE++eWOCUr502qaxCuk6lCmsuAv4ulw5/ejMtEu2Zr1WRYtDdJ0/wWz/O0eLgJKtwqNW4Nh33TuPJe4Ciyvbp/2HaYAv1qGBgnXXnTVCV5LYvCqQUOX6DjbFZxroz9bbIHDNxacc/NywG1gZ/ZodHiF8U3jRWdaqVoNXzkRYD8p//6uqKnZjZYCMWzdF/SMmE/mDbEPJ24IzP7GLX7NY190P0eP3Q7wLYjSMYmyR2OxgoyDLURD77klHsP7kGC54WmKGd2OM7bReyYvsWi3yATK2ZbR2kzNWuahuTefBDvEb4l8uPKz4HSNlVnI0kzjarNSw1MHWJ6ZBgutwb6+xKJdwtqpkSBCkeaWOY7J+qXu3IsNU6nL8/nE/Tx1Pde2bDlQie0CPfdIDlBU=
    -
      # LTD_PASSWORD
      secure: w4NsRHgsLvFP97Bnye3WmNC/Pr87wi8zVuMNdzQNjiJDEITDovvcPTe8y2ZBDZKsotoSSPw8Y8+jfaVTjjQtLTpD9jgsaHj4b1yyKpy0wXE+bgCMcggA8oGjrbdBgACSJx1aPgT56xT9yZjdnjbG1fVLWuLB/3uGJJn5q0TKXjqBocEj7r3NiGG5SWXupCrTvuvD8Ztp9N4bfumVTNhOTtfz2EZ3miYJLB8t5CFcPLjq+MzvpPo/7px/191OxORwKXB2mob4pY3FWsJYL/mIsHnHVfXG4K1qp+qb6RQq6hmQkO7Gwy2rT9MYLyVpw9Gs8Pbrq04wszikpbbXYXt7gjXvo4/sX49uhDhr+v0LOqsbdrM+yve65MWQ3KX/IvqoLfO2qvbbGoH4Mx5PlGKscfFJt9atS/s6NRUdY0V6XbP2JqLAHpYrh9hF5n+Xvvf30zJ45w8cpvFQNHsrtvxe0c+L9CJ/7iiu/E1bOZaEA3205Ghc+Hkc6nAVuEuaCBOuAxqJV3gZVvrfOnoKRkpbYcdJ50rz/AugLyQBSPbdMNeY1T2ZXIJ1hmYtxORy5es/B3ETXbshvmGZOTXsxiU72qufxrz24Fx9MN+FEWlnNVkeyACL64ZKLpaWngztouDy+5xr1xyVtoC7y3P7mHXcAmSw7i4WHBwybpGr9NC7T1I=
